### ISSUE TITLE
Allow change key_name in some nice way

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/m-aws-basic-infrastructure#14]
By default ec2_user is set up.

We should have possibility to create any number of clusters.
If you create second instance using the same image you will get error:

Error: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'ec2-user' already exists.

We should have possibility to pass username in some nice way (eg. variable, like it is with cluster name) - now it needs to be done by editing terraform files and rebuild image.

Or we need to think about some different solution for this.

Also we should consider to give possibility to setup default username on installed machine. Now it's ec2-user and there is no possibility to change it before deployment.

**Comment by sk4zuzu** [comment]
@plirglo this bug is not about changing admin's username. The real problem is here:
https://github.com/sk4zuzu/m-aws-basic-infrastructure/blob/develop/resources/terraform/main.tf#L2
```
key_name   = var.admin_username
```
The `key_name` has nothing to do with `admin_username`. :)

**Comment by atsikham** [comment]
@sk4zuzu should we pass it as a variable? May be hide it from user with https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair#key_name_prefix?

**Comment by sk4zuzu** [comment]
> @sk4zuzu should we pass it as a variable? May be hide it from user with https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair#key_name_prefix?

Ah I get it. It can be moved into the ec2 submodule. Go ahead :+1::innocent: Maybe we could make all the terraform code flat then? What is the benefit of having the ec2 submodule? :thinking:

**Comment by atsikham** [comment]
`key_name` replaced by `key_name_prefix` to avoid duplicates in this [PR](https://github.com/epiphany-platform/m-aws-basic-infrastructure/pull/24).

**Comment by atsikham** [comment]
Key name is unique now.
