### ISSUE TITLE
[BUG] No Internet access from awsbi instances when public ip are disabled

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/m-aws-basic-infrastructure#17]
**Describe the bug**
Awsbi should contain at least one NAT GW resource, otherwise there is no Internet access from instances without public ip address.

**Expected behavior**
Internet access should be enabled.

**Additional context** 

it's already implemented in AwsKS module, so it should be basically moved from there.

**Comment by atsikham** [comment]
Will be tested together with [related](https://github.com/epiphany-platform/m-aws-kubernetes-service/issues/12) issue.

**Comment by atsikham** [comment]
NAT gateway is used for internet access if there are no public IPs.
