### ISSUE TITLE
Add requirements information in readme (ie.: make, docker)

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-aws-basic-infrastructure#2]
**Is your feature request related to a problem? Please describe.**
We don't have right now information about requirements in a readme.  

**Describe the solution you'd like**
We want to have requirements part in the readme that will cover information about for example - `make`, `docker`, OS that are necessary to build module.

**Describe alternatives you've considered**
None.

**Additional context**
_Originally posted by @atsikham in https://github.com/epiphany-platform/m-aws-basic-infrastructure/pull/1#issuecomment-698280431_

**Comment by mkyc** [comment]
In [another repo there is method](https://github.com/epiphany-platform/m-azure-basic-infrastructure/blob/develop/tests/suite.sh#L6) checking if requirements are met. We could add this kind of self check and documentation line in readme.

**Comment by atsikham** [comment]
Need to include a note from #1700 task about windows support.

**Comment by rafzei** [comment]
Available variables for docker init should be placed in the readme.md as well:
```
  * M_VMS_COUNT = < instance count > (default: 1)
  * M_PUBLIC_IPS =  < true/false > (default: true)
  * M_NAME = < module name > (default: epiphany)
  * M_VMS_RSA = < ssh priv key name > (defailt: vms_rsa)
  * M_REGION = < aws region > (default: eu-central-1)
  * M_OS = < ubuntu/redhat > (default: ubuntu)
```
