### ISSUE TITLE
[FEATURE REQUEST] AWS VPC needs to be fully HA for production environments

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/m-aws-basic-infrastructure#20]
**Is your feature request related to a problem? Please describe.**
Currently awsbi has only 1 private subnet, only 1 public subnet, only 1 nat gateway and uses only 1 availability zone. This is not providing HA capabilities.

**Describe the solution you'd like**
At least 3 AZ supported, 3 public subnets, 3 private subnets, 3 NAT gateways supported with an option to reduce number of NAT gateways to 1 for non-prod environments (cost reduction).

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by atsikham** [comment]
According to requirements of this task, It's done in #40

**Comment by atsikham** [comment]
Implemented together with #6 in PR #40. Check docs/INPUT.adoc for new/changed parameters.

**Comment by przemyslavic** [comment]
Tested together with #6 (PR #40).
