### ISSUE TITLE
Add the ability to extend root disk size

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/m-aws-basic-infrastructure#21]
**Is your feature request related to a problem? Please describe.**
At the moment VMs that are created by the module have disk size of 10 GiB. Discussed with @to-bar that it's not enough at least for repository machine where (in long term) we need 64. Need to add an ability to change that.

**Describe the solution you'd like**
Add module's parameter(s) to extend disk size.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by sk4zuzu** [comment]
This is really a show stopper for people wanting to deploy epiphany on those vms! :scream:

**Comment by mkyc** [comment]
@plirglo and @rafzei can you maybe confirm disk sizes you had? We need to test it ASAP.

**Comment by rafzei** [comment]
@mkyc confirmed, I've 64GB volume size on instances
```
      + root_block_device {
          + delete_on_termination = true
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = 64
          + volume_type           = (known after apply)
        }
    }
```
