### ISSUE TITLE
Remove resources after failed test deployments

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/m-aws-basic-infrastructure#26]
**Is your feature request related to a problem? Please describe.**
After failed integration tests for AWS infrastructure module there can left objects on AWS attached to given resource group.

**Describe the solution you'd like**
We wan't to have solution in tests that is cleaning remaining resources.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by erzetpe** [comment]
PR [26](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/26)

**Comment by przemyslavic** [comment]
Added tests for: `init`, `plan`, `apply`, `destroy plan`, `destroy`.
Tests can be run with `make test` or `go test` command.

**Comment by przemyslavic** [comment]
Removing AWS resources done in [25](https://github.com/epiphany-platform/m-aws-basic-infrastructure/pull/25).
