### ISSUE TITLE
Introduce definition of VM groups

### ISSUE THREAD

**Issue by ar3ndt** [epiphany-platform/m-aws-basic-infrastructure#27]
**Is your feature request related to a problem? Please describe.**
We need an option to specify VM groups. the use case example is when we have different Epiphany components and each of them requires VMs configured according to resources consumption.

**Describe the solution you'd like**
Add an ability to define VM groups and configure it with module parameters.
Parameters need to be defined for VM group:

* VM type (CPU, RAM)
* base OS image
* OS disk size
* additional non-OS disks
* subnet id for the group that is taken from `subnets` parameter implemented in #43 task
* additional security group settings / instance profiles
* enable/disable public IP addresses
* at this stage we should not be using autoscaling groups for hadling single VMs (we made this mistake before)

**Describe alternatives you've considered**
No.

**Additional context**
Original task description:
We need to implement possibility of setting virtual machine sizes when deploying Epiphany. New option `vm_size` should be introduced. It might make sense to provide sizes for each subnet as proposed in #14 or introduce a VMs grouping. This is similar to already existing task for Azure:
https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/13

**Comment by rafzei** [comment]
I think it's clear. Please refer to links in issue description.

**Comment by toszo** [comment]
Size should be defined depending on group (component) that will be installed on VM. For ex. Kafka needs different machine size than RabbitMQ.

**Comment by atsikham** [comment]
Please also groom similar task in `azbi` module - https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/13

**Comment by sk4zuzu** [comment]
> Size should be defined depending on group (component) that will be installed on VM. For ex. Kafka needs different machine size than RabbitMQ.

IMO, basically in a single group we should be able to:
- define VM type (CPU, RAM)
- define base OS image
- define OS disk size
- define additional non-OS disks
- define subnet(s) for the group, but it should be also possible to span multiple groups across single subnet (per AZ)
- define additional security group settings / instance profiles
- enable/disable public IP addresses
- at this stage we should not be using autoscaling groups for hadling single VMs (we made this mistake before)

:thinking:

**Comment by DaOsie** [comment]
This parameter is used in the module that creates single virtual machine, therefore I wouldn't discuss groups here - they suppose to be discussed in different abstraction layer that uses this module. Simple vm_size parameter should do the job now.

**Comment by atsikham** [comment]
@sk4zuzu @DaOsie I still think VM groups should be implemented here, see the comment from @toszo 
Anyway, if it's not implemented here, please create a new task about VM groups. It shouldn't be lost.

**Comment by sk4zuzu** [comment]
Update after duscussion:
> * define VM type (CPU, RAM)
> * define base OS image
> * define OS disk size
> * define additional non-OS disks
> * define subnet(s) for the group, but it should be also possible to span multiple groups across single subnet (per AZ)
> * define additional security group settings / instance profiles
> * enable/disable public IP addresses
> * at this stage we should not be using autoscaling groups for hadling single VMs (we made this mistake before)

> * define subnet(s) for the group, but it should be also possible to span multiple groups across single subnet (per AZ)

The idea is here to pre-define arbitrary number of subnets and assign arbitrary number of VM groups (not single VMs!) to those subnets in any order user wants, for example 2 subnets and 5 groups would split 2(1 and 3 group)/3(2,4 and 5 group). The `define subnet(s) for the group` seems to be unreasonable and seems to have no use in our infrastructure, also IMO it would make terraform code more complex for no apparent reason.

WDYT? :thinking:

**Comment by rpudlowski93** [comment]
Done in PR #56

Should be review together with task #55

**Comment by przemyslavic** [comment]
The ability to create multiple  VM groups has been added.
What has been tested:
- possibility to set vm image specification
- possibility to define instance count and vm size
- possibility to customise data disks
- possibility to customise security groups
- possibility to customise subnets
- possibility to enable/disable public IPs
