### ISSUE TITLE
Add possibility to pass image name (terraform) as variable

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/m-aws-basic-infrastructure#28]
We use ami: "ami-02ab606eae7264892" which is accessible only in eu-central-1 region. and this cannot be changed without code modyfication and image rebuild.
That means it's impossible to use it in any other region.

We need to have possibility to pass this as variable:
docker run ... -e M_AMI="some image"

And maybe also we should provide list of supported amis per region.

**Comment by rafzei** [comment]
We provided posibility to specify M_REGION but not M_AMI.
`AMI IDs are unique to each AWS Region.` ->[source](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html#finding-an-ami-console)
In 'clasic' Epiphany we are doing some filtering by OS full name in python code.

**Comment by atsikham** [comment]
@rafzei Could you describe what was done in this task to test?

**Comment by rafzei** [comment]
> @rafzei Could you describe what was done in this task to test?

- all-destroy make target
- var.os - new variable
- data source: aws_ami - selecting ami depending on var.os

**Comment by atsikham** [comment]
Verified with `M_OS` possible `redhat` and `ubuntu` values.
