### ISSUE TITLE
Create rules to open communication between created machines

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/m-aws-basic-infrastructure#33]
**Is your feature request related to a problem?** 

Communication between machines in cluster does not work on ports other than 22.

**Describe the solution you'd like**

We need to add rules to security group to allow communication on ports needed to run epiphany cluster. At least ports described [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/SECURITY.md)

**Describe alternatives you've considered**

**Additional context**

**Comment by atsikham** [comment]
I think that as modules can be used not only for Epiphany installation, it should be configurable, may be with default rules that is necessary for Epiphany and listed in the doc @plirglo provided.

**Comment by atsikham** [comment]
Check how it can be connected to #27.

**Comment by przemyslavic** [comment]
The possibility to define multiple security groups and rules for controlling inbound and outbound traffic has been added. Tested by passing a value for the `M_SECURITY_GROUPS` parameter for the init command and then checked rules in the AWS management console.
