### ISSUE TITLE
Add support for disks/volumes customization

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/m-aws-basic-infrastructure#37]
**Is your feature request related to a problem? Please describe.**
This task is created after grooming of [another](https://github.com/epiphany-platform/epiphany/issues/139) one in epiphany classic. It's necessary to customize disks creation at least per application.

**Describe the solution you'd like**
Add an ability to customize disks/volumes.

**Describe alternatives you've considered**
None.

**Additional context**
Implementation of this task should be started after #27

**Comment by rpudlowski93** [comment]
Done in PR #56

Should be review together with #55

**Comment by przemyslavic** [comment]
@rpudlowski93 I see there was added the ability to specify additional data disks. But I don't see an option to set the size of the root volume. Can you comment on that?

**Comment by atsikham** [comment]
Discussed that with @mkyc as he introduced similar changes in Azure.

I think we need to do following steps:
1. Check If filesystem is resized automaticaly when new size of OS disk is specified. Should be checked with all supported operating systems.
2. If there is automatic resizing, add support for custom root disk size:

```
root_block_device {
    volume_size = var.root_volume_size
}
```

3. If it's the same as in Azure, leave it as is and introduce only after "host init" module implementation.

**Comment by rpudlowski93** [comment]
In AWS, we can specify root volume size and the OS volume size will be resized automatically so I added to possibility to specify root volume size in the following PR: #58. 
I checked it for Ubuntu and Redhat OS: 
- RHEL-7.8_HVM_GA-20200225-x86_64-1-Hourly2-GP2
- ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20200611

**Comment by przemyslavic** [comment]
An option to set the root volume size has been added.
If the user sets the disk size too small (smaller than required by the system image), terraform returns an error message:
RHEL
```
Error: Error launching source instance: InvalidBlockDeviceMapping: Volume of size 6GB is smaller than  snapshot 'snap-xxx', expect size >= 10GB
        status code: 400, request id: xxx
```
Ubuntu
```
Error: Error launching source instance: InvalidBlockDeviceMapping: Volume of size 5GB is smaller than  snapshot 'snap-xxx', expect size >= 8GB
        status code: 400, request id: xxx
```

**Comment by mkyc** [comment]
In current way we do it there is no way we can validate this.
