### ISSUE TITLE
Integrate tests with test pipeline

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/m-aws-basic-infrastructure#38]
**Is your feature request related to a problem? Please describe.**
We can run integration tests manually, but right now we don't have possibility to take output from tests and calling them from test pipelines.

**Describe the solution you'd like**
We want to run tests from test pipelines with and present test results in form similar to junit.

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by atsikham** [comment]
Is there more work than something like this?

```
go test -v -timeout 30m 2>&1 | tee tests.output
go-junit-report < tests.output > report.xml
```

Can't it be done in the scope of https://github.com/epiphany-platform/epiphany/issues/1761?

**Comment by ar3ndt** [comment]
it was done in scope of 1761 indeed

**Comment by przemyslavic** [comment]
Done in [1761](https://github.com/epiphany-platform/epiphany/issues/1761).
