### ISSUE TITLE
[BUG] Resource names are not displayed on AWS.

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/m-aws-basic-infrastructure#48]
**Describe the bug**
Resource names are not displayed on AWS. The `Name` field is empty, which is different from the classic Epiphany.

**How to reproduce**
1. Deploy the awsbi module.
2. Check resource names on AWS (Instance name, VPC name, subnet name...)

**Expected behavior**
The names are displayed correctly in the list.

**Actual behavior**
The name field is empty.

![image](https://user-images.githubusercontent.com/43173646/102191455-b5820100-3eb9-11eb-9223-a7e83ac239f6.png)
![image](https://user-images.githubusercontent.com/43173646/102191494-c7fc3a80-3eb9-11eb-91a7-c869d0b08bc2.png)
![image](https://user-images.githubusercontent.com/43173646/102191552-dc403780-3eb9-11eb-8b7d-08daaebf84e7.png)

**Comment by atsikham** [comment]
The couse of this issue is wrong tag keys. It matters if there is `Name` or `name` and in the second case there are no resource names displayed.

**Comment by przemyslavic** [comment]
Fixed. Resources are now tagged correctly and their names are displayed in the main list.
