### ISSUE TITLE
Unify docker image name across module

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-aws-basic-infrastructure#50]
Mirror of task [38 from another module](https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/38). And [here](https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/55) is related PR.

**Comment by mkyc** [comment]
#65 also covers this issue

**Comment by przemyslavic** [comment]
Tested together with task #59.
:heavy_check_mark: After fixing (PR #69) the pipeline works fine and test results are visible in Azure DevOps.
