### ISSUE TITLE
[FEATURE REQUEST] Ability to create fully private VPC

### ISSUE THREAD

**Issue by rpudlowski93** [epiphany-platform/m-aws-basic-infrastructure#55]
**Is your feature request related to a problem? Please describe.**
Right now, we must create always at least one public subnet what means that we don't have possibilities to create fully private cluster. We create always IGW, one public subnet and route table association from the public subnet to the IGW even if we don't create any instance in public subnet and NAT gateway. 

It looks like a mistake in architecture solution, a little similar to the scenario: https://docs.amazonaws.cn/en_us/vpc/latest/userguide/VPC_Scenario2.html

**Describe the solution you'd like**
I would like to have possibilities to create fully private cluster, like in this scenario:
https://docs.amazonaws.cn/en_us/vpc/latest/userguide/VPC_Scenario4.html

**Describe alternatives you've considered**
I would like to have some configuration parameter such as "private_cluster: true/false"

**Additional context**
It could be awesome to have possibilities to create VPC in every scenario which is mentioned here: https://docs.amazonaws.cn/en_us/vpc/latest/userguide/VPC_wizard.html

**Comment by rpudlowski93** [comment]
Done in PR #56. 

Should be review together with task #27

**Comment by przemyslavic** [comment]
The ability to create a Virtual Private Gateway has been added to create fully private cluster.
