### ISSUE TITLE
[FEATURE REQUEST] Rewrite module code to GO

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/m-aws-basic-infrastructure#59]
**Is your feature request related to a problem? Please describe.**
Current code is in makefiles, we need to translate it to golang.

**Describe the solution you'd like**
rewrite run logic

**Describe alternatives you've considered**
n/a

**Additional context**
tests are already ported
run code would be very similar to AzBI
e-structures are to be implemented

**Comment by przemyslavic** [comment]
Tested:
:heavy_check_mark: init
:heavy_check_mark: plan
:heavy_check_mark: apply
:heavy_check_mark: metadata
:heavy_check_mark: metadata --json
:heavy_check_mark: output
:heavy_check_mark: plan --destroy
:heavy_check_mark: destroy
:heavy_check_mark: make test
:heavy_check_mark: make pipeline-test + additionally ran Azure DevOps pipeline

Also checked `--name`, `--region` and `--vms-rsa` parameteres for `init` command and `--debug` for all the commands.

Created tasks:
#70
#71
