### ISSUE TITLE
Allow creation of additional subnets

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/m-aws-basic-infrastructure#6]
**Is your feature request related to a problem? Please describe.**
At the moment private subnets for EKS are created in aws-eks module directly, when it's an infrastructure part.
**Describe the solution you'd like**
Now only one subnet is created by the module and it's public. Need to add an ability to specify additional subnets, their cidr range and availability zone.
**Describe alternatives you've considered**
No.
**Additional context**

Additional information:
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Scenario2.html

Expectations:
1. Infrastructure part that is created in AWS-EKS module is moved to this module.
2. At least following resources creation parametrized: _subnets_, their _cidr range_ and _availability zone_.

**Comment by sk4zuzu** [comment]
Update:
After this PR/fix https://github.com/epiphany-platform/m-aws-basic-infrastructure/pull/19 we have now 2 subnets and 1 nat gateway inside the awsbi module, which is a step closer to achieve the goal. :+1:

**Comment by sk4zuzu** [comment]
I think this issue is realated to https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/20
Please take a look as well :)

**Comment by atsikham** [comment]
Please consider specifying tags to subnets. It's necessary for example for EKS and nice to have this ability for those who use `awsbi` and `awsks` together to create k8s cluster from scratch. 
Check this article - https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html#vpc-subnet-tagging.

**Comment by atsikham** [comment]
PR #40 also contains #20 task implemented as these 2 tasks are related to each other as @sk4zuzu mentioned.

**Comment by przemyslavic** [comment]
Successfully deployed the awsbi module with 3 public subnets, 3 private subnets (in separate availability zones) and 3 NAT gateways.
